Update 'liftIO' usage and commented 'cm_import' in 'CoreModule', as it's no longer available.
src/Zeno/HaskellParser.hs:126:15: Not in scope: ‘Hs.liftIO’

src/Zeno/HaskellParser.hs:129:7:
    ‘Hs.cm_imports’ is not a (visible) field of constructor ‘Hs.CoreModule’

src/Zeno/HaskellParser.hs:129:23:
    Not in scope: ‘Hs.cg_dir_imps’
    Perhaps you meant ‘Hs.mg_dir_imps’ (imported from HscTypes)